export const base = {
  breakpoints: [],
  space: [],
  fonts: {

  }
}

export const light = {
  "bgColor": "#F4F7FD",
  "navColor": "#FFFFFF",
  "navIconTileOne": "#635FC7",
  "navIconTileTwo": "#635fc7bf",
  "navIconTileThree": "#635fc780",
  "navLogoTitleTextColor": "#000112",
  "sidebarBorderColor": "#E4EBFA",
  "sidebarBoardCountTextColor": "#828FA3",
  "sidebarBoardItemBGColor": "#635FC7",
  "sidebarBoardItemBGColorHover": "#635fc72b",
  "sidebarBoardItemTextColor": "#828FA3",
  "sidebarBoardItemTextColorHover": "#635FC7",
  "sidebarBoardItemActiveTextColor": "#FFFFFF",
  "sidebarCreateBoardButtonTextColor": "#635FC7",
  "sidebarThemeBGColor": "#F4F7FD",
  "sidebarHideButtonTextColor": "#828FA3",
  "sidebarOpenButtonBGColor": "#635FC7",
  "sidebarOpenButtonBGColorHover": "#A8A4FF",
  "sidebarOpenButtonTextColor": "#FFFFFF",
  "sidebarDropdownBGColor": "#635FC7",
  "sidebarDropdownBGColorHover": "#A8A4FF",
  "optionsContentBGColor": "#FFFFFF",
  "taskTitleColor": "#000112",
  "buttonBGColor": "#635FC7",
  "buttonFontColor": "#FFFFFF",
  "buttonDotColor": "#828FA3",
  "noColumnButtonBGColor": "#635FC7",
  "noColumnButtonBGColorHover": "#A8A4FF",
  "noColumnTextColor": "#828FA3",
  "columnNameTextColor": "#828FA3",
  "taskBGColor": "#FFFFFF",
  "taskTitleTextColor": "#000112",
  "taskTitleTextColorHover": "#635FC7",
  "taskSubtaskCountTextColor": "#828FA3",
  "taskStatusColor1": "#49C4E5",
  "taskStatusColor2": "#8471F2",
  "taskStatusColor3": "#67E2AE",
  "taskViewCardBGColor": "#FFFFFF",
  "taskViewCardTitleTextColor": "#000112",
  "taskViewCardDescriptionTextColor": "#828FA3",
  "subtaskViewCardTitleTextColor": "#828FA3",
  "subtaskViewCardBGColor": "#F4F7FD",
  "subtaskViewCardBGColorHover": "#635FC7",
  "subtaskViewCardTextColor": "#000112",
  "subtaskViewCardMarkBGColor": "#FFFFFF",
  "dropdownCurrentValueTextColor": "#000112",
  "dropdownOptionsBGColor": "#FFFFFF",
  "createButtonPanelBGColor": "linear-gradient(180deg, #E9EFFA 0%, rgba(233, 239, 250, 0.5) 100%)",
  "createButtonPanelTextColor": "#828FA3",
  "createButtonPanelTextColorHover": "#635FC7"
}

export const dark = {
  "bgColor": "#20212C",
  "navColor": "#2B2C37",
  "navIconTileOne": "#635FC7",
  "navIconTileTwo": "#635fc7bf",
  "navIconTileThree": "#635fc780",
  "navLogoTitleTextColor": "#FFFFFF",
  "sidebarBorderColor": "#3E3F4E",
  "sidebarBoardCountTextColor": "#828FA3",
  "sidebarBoardItemBGColor": "#635FC7",
  "sidebarBoardItemBGColorHover": "#FFFFFF",
  "sidebarBoardItemTextColor": "#828FA3",
  "sidebarBoardItemTextColorHover": "#635FC7",
  "sidebarBoardItemActiveTextColor": "#FFFFFF", 
  "sidebarCreateBoardButtonTextColor": "#635FC7",
  "sidebarThemeBGColor": "#20212C",
  "sidebarHideButtonTextColor": "#828FA3",
  "sidebarOpenButtonBGColor": "#635FC7",
  "sidebarOpenButtonBGColorHover": "#A8A4FF",
  "sidebarOpenButtonTextColor": "#FFFFFF",
  "sidebarDropdownBGColor": "#635FC7",
  "sidebarDropdownBGColorHover": "#A8A4FF",
  "optionsContentBGColor": "#20212C",
  "taskTitleColor": "#FFFFFF",
  "buttonBGColor": "#635FC7",
  "buttonFontColor": "#FFFFFF",
  "buttonDotColor": "#828FA3",
  "noColumnButtonBGColor": "#635FC7",
  "noColumnButtonBGColorHover": "#A8A4FF",
  "noColumnTextColor": "#828FA3",
  "columnNameTextColor": "#828FA3",
  "taskBGColor": "#2B2C37",
  "taskTitleTextColor": "#FFFFFF",
  "taskTitleTextColorHover": "#635FC7",
  "taskSubtaskCountTextColor": "#828FA3",
  "taskStatusColor1": "#49C4E5",
  "taskStatusColor2": "#8471F2",
  "taskStatusColor3": "#67E2AE",
  "taskViewCardBGColor": "#2B2C37",
  "taskViewCardTitleTextColor": "#FFFFFF",
  "taskViewCardDescriptionTextColor": "#828FA3",
  "subtaskViewCardTitleTextColor": "#FFFFFF",
  "subtaskViewCardBGColor": "#20212C",
  "subtaskViewCardBGColorHover": "#635FC7",
  "subtaskViewCardTextColor": "#FFFFFF",
  "subtaskViewCardMarkBGColor": "#2B2C37",
  "dropdownCurrentValueTextColor": "#FFFFFF",
  "dropdownOptionsBGColor": "#20212C",
  "createButtonPanelBGColor": "linear-gradient(180deg, rgba(43, 44, 55, 0.25) 0%, rgba(43, 44, 55, 0.125) 100%)",
  "createButtonPanelTextColor": "#828FA3",
  "createButtonPanelTextColorHover": "#635FC7"
}