export const base = {
  breakpoints: [],
  space: [],
  fonts: {

  }
}

export const light = {
  "bgColor": "#F4F7FD",
  "navColor": "#FFFFFF",
  "navIconTileOne": "#635FC7",
  "navIconTileTwo": "#635fc7bf",
  "navIconTileThree": "#635fc780",
  "navLogoTitleTextColor": "#000112",
  "sidebarBorderColor": "#E4EBFA",
  "sidebarBoardCountTextColor": "#828FA3",
  "sidebarBoardItemBGColor": "#635FC7",
  "sidebarBoardItemBGColorHover": "#635fc72b",
  "sidebarBoardItemTextColor": "#828FA3",
  "sidebarBoardItemTextColorHover": "#635FC7",
  "sidebarBoardItemActiveTextColor": "#FFFFFF",
  "sidebarCreateBoardButtonTextColor": "#635FC7",
  "sidebarThemeBGColor": "#F4F7FD",
  "sidebarHideButtonTextColor": "#828FA3",
  "sidebarOpenButtonBGColor": "#635FC7",
  "sidebarOpenButtonBGColorHover": "#A8A4FF",
  "sidebarOpenButtonTextColor": "#FFFFFF",
  "sidebarDropdownBGColor": "#635FC7",
  "sidebarDropdownBGColorHover": "#A8A4FF",
  "taskTitleColor": "#000112",
  "buttonBGColor": "#635FC7",
  "buttonFontColor": "#FFFFFF",
  "buttonDotColor": "#828FA3",
  "noColumnButtonBGColor": "#635FC7",
  "noColumnButtonBGColorHover": "#A8A4FF",
  "noColumnTextColor": "#828FA3",
  "columnNameTextColor": "#828FA3",
  "taskBGColor": "#FFFFFF",
  "taskTitleTextColor": "#000112",
  "taskTitleTextColorHover": "#635FC7",
  "taskSubtaskCountTextColor": "#828FA3",
  "taskStatusColor1": "#49C4E5",
  "taskStatusColor2": "#8471F2",
  "taskStatusColor3": "#67E2AE",
  "createButtonPanelBGColor": "#E9EFFA",
  "createButtonPanelTextColor": "#828FA3",
  "createButtonPanelTextColorHover": "#635FC7"
}

export const dark = {
  "bgColor": "#20212C",
  "navColor": "#2B2C37",
  "navIconTileOne": "#635FC7",
  "navIconTileTwo": "#635fc7bf",
  "navIconTileThree": "#635fc780",
  "navLogoTitleTextColor": "#FFFFFF",
  "sidebarBorderColor": "#3E3F4E",
  "sidebarBoardCountTextColor": "#828FA3",
  "sidebarBoardItemBGColor": "#635FC7",
  "sidebarBoardItemBGColorHover": "#FFFFFF",
  "sidebarBoardItemTextColor": "#828FA3",
  "sidebarBoardItemTextColorHover": "#635FC7",
  "sidebarBoardItemActiveTextColor": "#FFFFFF",
  "sidebarCreateBoardButtonTextColor": "#635FC7",
  "sidebarThemeBGColor": "#20212C",
  "sidebarHideButtonTextColor": "#828FA3",
  "sidebarOpenButtonBGColor": "#635FC7",
  "sidebarOpenButtonBGColorHover": "#A8A4FF",
  "sidebarOpenButtonTextColor": "#FFFFFF",
  "sidebarDropdownBGColor": "#635FC7",
  "sidebarDropdownBGColorHover": "#A8A4FF",
  "taskTitleColor": "#FFFFFF",
  "buttonBGColor": "#635FC7",
  "buttonFontColor": "#FFFFFF",
  "buttonDotColor": "#828FA3",
  "noColumnButtonBGColor": "#635FC7",
  "noColumnButtonBGColorHover": "#A8A4FF",
  "noColumnTextColor": "#828FA3",
  "columnNameTextColor": "#828FA3",
  "taskBGColor": "#2B2C37",
  "taskTitleTextColor": "#FFFFFF",
  "taskTitleTextColorHover": "#635FC7",
  "taskSubtaskCountTextColor": "#828FA3",
  "taskStatusColor1": "#49C4E5",
  "taskStatusColor2": "#8471F2",
  "taskStatusColor3": "#67E2AE",
  "createButtonPanelBGColor": "#2B2C37",
  "createButtonPanelTextColor": "#828FA3",
  "createButtonPanelTextColorHover": "#635FC7"
}